name: build
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@v2

      - name: Test Go code
        run: go test -race -coverprofile=cover.out -covermode=atomic

      - name: Upload coverage report to CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./cover.out